--- 
title: "Statistical Models"
author: "Dale J. Barr"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Third-year course of the Psychology Department at the University of Glasgow's #psyteachr series."
---

```{r cite-packages, include = FALSE}
# automatically create a bib database for R packages
# add any packages you want to cite here
knitr::write_bib(c(
  .packages(), 'bookdown', 'tidyverse', 'kableExtra'
), 'packages.bib')

```

# Overview {-}

This course teaches students how to translate psychological study designs into statistical models. The course adopts a General Linear Models approach, with an emphasis on data simulation, reproducibility, and transparency. Students will learn how to simulate and analyze data from many different common designs in psychology. 

## Course Aims

- To provide an understanding of the basic statistics appropriate to the analysis of psychological experiments.
- To learn how to produce reproducible scripts and reports using R and RMarkdown.

## Intended Learning Outcomes

By the end of this course students will be able to:

- Integrate knowledge about study design and statistics to formulate and estimate the General Linear Model (GLM) appropriate to the various types of study designs encountered in psychology, especially studies with repeated observations.
- Visualise and interpret various effects (including interactions) in multi-way designs.
- Estimate linear mixed-effects models and describe their relation to traditional techniques such as ANOVA and multiple regression.
- Perform logistic regression and explain and interpret the statistical output.
- Create reproducible data analysis scripts and reports within the R statistical programming environment.
